# Generated by Django 3.0.3 on 2020-06-27 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_remove_userprofile_userindex'),
        ('article', '0003_auto_20200626_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('intro', models.TextField()),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='group.group')),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='articleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.article')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='group.group')),
            ],
        ),
    ]
