# Generated by Django 3.0.3 on 2020-06-28 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_article_group'),
        ('group', '0002_delete_articlegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='articleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.article')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='group.group')),
            ],
        ),
    ]
