# Generated by Django 3.0.3 on 2020-07-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_articlegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
