# Generated by Django 3.0.3 on 2020-08-10 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20200810_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlegroup',
            name='categories',
        ),
        migrations.AlterField(
            model_name='articlegroup_category',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='group.articleGroup'),
        ),
    ]
