# Generated by Django 3.0.3 on 2020-08-10 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_category_creater'),
        ('group', '0009_auto_20200810_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlegroup_category',
            name='group',
        ),
        migrations.RemoveField(
            model_name='articlegroup_category',
            name='name',
        ),
        migrations.AddField(
            model_name='articlegroup_category',
            name='articleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='article.article'),
        ),
        migrations.CreateModel(
            name='group_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未分類', max_length=100)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='group.group')),
            ],
        ),
        migrations.AddField(
            model_name='articlegroup_category',
            name='categoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='group.group_category'),
        ),
    ]
