# Generated by Django 3.0.3 on 2020-08-10 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_category_creater'),
        ('group', '0010_auto_20200810_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegroup_category',
            name='articleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.article'),
        ),
        migrations.AlterField(
            model_name='articlegroup_category',
            name='categoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='group.group_category'),
        ),
    ]
