# Generated by Django 3.0.3 on 2020-08-10 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_auto_20200810_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlegroup_category',
            name='groupID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='group.group'),
        ),
    ]
