# Generated by Django 3.0.3 on 2020-08-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_articlegroup_category_groupid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlegroup_category',
            name='groupID',
        ),
    ]
