# Generated by Django 2.2.5 on 2020-09-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_userprofile_userindex'),
        ('group', '0014_auto_20200811_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.UserProfile')),
            ],
        ),
    ]
