# Generated by Django 2.2.5 on 2020-09-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_auto_20200925_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_category',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
    ]
