# Generated by Django 2.2.5 on 2020-09-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_auto_20200930_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegroup',
            name='articleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
        migrations.AlterField(
            model_name='articlegroup',
            name='groupID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
        migrations.AlterField(
            model_name='articlegroup_category',
            name='articleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
        migrations.AlterField(
            model_name='articlegroup_category',
            name='categoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group_category'),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.UserProfile'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.UserProfile'),
        ),
    ]
