# Generated by Django 2.2.5 on 2020-10-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0017_auto_20200930_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='privacy',
            field=models.IntegerField(default=0),
        ),
    ]
