# Generated by Django 3.0.3 on 2020-06-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.IntegerField(default=0),
        ),
    ]
