# Generated by Django 3.0.3 on 2020-06-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='group',
        ),
    ]
