# Generated by Django 3.0.3 on 2020-07-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200710_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未分類', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categorys',
            field=models.ManyToManyField(to='article.category'),
        ),
    ]
