# Generated by Django 3.0.3 on 2020-07-14 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_userprofile_userindex'),
        ('article', '0008_auto_20200714_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.UserProfile'),
        ),
    ]
