# Generated by Django 3.0.3 on 2020-09-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20200916_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.FloatField(default=0),
        ),
    ]
