# Generated by Django 3.0.3 on 2020-09-19 12:39

from django.db import migrations, models
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20200919_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=simditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='pubtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
