# Generated by Django 3.0.3 on 2020-06-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mName', models.CharField(max_length=20)),
                ('mSex', models.CharField(default='M', max_length=2)),
                ('mAccount', models.CharField(max_length=20)),
                ('mPassword', models.CharField(max_length=20)),
            ],
        ),
    ]
