# Generated by Django 3.0.3 on 2020-06-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userIndex',
        ),
    ]
